# Generated by Django 4.0.3 on 2024-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Image2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image2', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
