# Generated by Django 4.0.3 on 2024-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image1',
            name='sequence_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='image2',
            name='sequence_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='image1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
