# Generated by Django 4.0.3 on 2024-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mash', '0003_image_delete_image1_delete_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
