# Generated by Django 4.0.3 on 2024-05-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mash', '0004_alter_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mash.image')),
            ],
        ),
    ]
